[workspace]
default-members = [
    "i18n_inflector",
]
members = [
    "i18n_inflector",
]
resolver = "3"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["internationalization", "localization", "no-std"]
edition = "2024"
keywords = ["inflector", "internationalization", "localization", "i18n", "l10n"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/theseus-rs/i18n-inflector"
rust-version = "1.97.1"
version = "0.4.0"

[workspace.lints.rust]
dead_code = "allow"
missing_debug_implementations = "deny"
unsafe_code = "deny"
unused_qualifications = "deny"
warnings = "deny"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
allow_attributes = "deny"
expect_used = "deny"
fallible_impl_from = "deny"
indexing_slicing = "deny"
large_stack_arrays = "allow"
mod_module_files = "deny"
panic = "deny"
panic_in_result_fn = "deny"
todo = "deny"
unreachable = "deny"
unimplemented = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"

[workspace.dependencies]
criterion = "0.8.2"
icu_locale = { version = "2.2.0", default-features = false, features = ["compiled_data"] }
icu_locale_core = { version = "2.2.0", default-features = false, features = ["alloc"] }
icu_normalizer = { version = "2.2.0", default-features = false, features = ["compiled_data"] }
